BOARD_SIZE = 15
TILEBOX_SIZE = 7

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700


FIELD_RECTANGLE = (32, 32)
FIELD_RECTANGLE_WIDTH = FIELD_RECTANGLE[0] + 2
LEFT_EDGE_BOARD_OFFSET = (WINDOW_WIDTH - FIELD_RECTANGLE_WIDTH * BOARD_SIZE) // 2 - FIELD_RECTANGLE_WIDTH
TOP_EDGE_BOARD_OFFSET = 100
BOARD_WIDTH = BOARD_SIZE * FIELD_RECTANGLE_WIDTH
TOP_EDGE_TILEBOX_OFFSET = 650
LEFT_EDGE_TILEBOX_OFFSET = (WINDOW_WIDTH - FIELD_RECTANGLE_WIDTH * TILEBOX_SIZE) // 2 - FIELD_RECTANGLE_WIDTH
