FONT_PATH = "./font/GameofThrones.ttf"
BOARD_SIZE = 15
TILEBOX_SIZE = 7

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700

FIELD_RECTANGLE = (34, 34)
FIELD_RECTANGLE_WIDTH = FIELD_RECTANGLE[0] + 2
LEFT_EDGE_BOARD_OFFSET = (WINDOW_WIDTH -
                          FIELD_RECTANGLE_WIDTH * BOARD_SIZE) // 2
TOP_EDGE_BOARD_OFFSET = 100
BOARD_WIDTH = BOARD_SIZE * FIELD_RECTANGLE_WIDTH

TOP_EDGE_TILEBOX_OFFSET = 650
LEFT_EDGE_TILEBOX_OFFSET = (WINDOW_WIDTH -
                            FIELD_RECTANGLE_WIDTH * TILEBOX_SIZE) // 2
TILEBOX_WIDTH = TILEBOX_SIZE * FIELD_RECTANGLE_WIDTH

ACTIVE_FIELD_BORDER_SIZE = 2

SCOREBOARD_SHAPE = (200, 200)
TOP_EDGE_SCOREBOARD_OFFSET = (WINDOW_HEIGHT - SCOREBOARD_SHAPE[1]) // 2
LEFT_EDGE_SCOREBOARD_OFFSET = 785

TITLE_SHAPE = (100, 600)
TOP_EDGE_TITLE_OFFSET = (WINDOW_HEIGHT - TITLE_SHAPE[1]) // 2
LEFT_EDGE_TITLE_OFFSET = (WINDOW_WIDTH - TITLE_SHAPE[0]) // 2

DIFFICULTY_DASH_SHAPE = (190, 70)
TOP_EDGE_DIFFICULTY_DASH_OFFSET = (300 - DIFFICULTY_DASH_SHAPE[1]) // 2
LEFT_EDGE_DIFFICULTY_DASH_OFFSET = (220 - DIFFICULTY_DASH_SHAPE[0]) // 2
